services:
  postgres:
    image: postgres:16-alpine
    container_name: scheduler-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: scheduler
      POSTGRES_PASSWORD: scheduler
      POSTGRES_DB: scheduler_db
    volumes:
      - /opt/scheduler/data/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U scheduler -d scheduler_db"]
      interval: 5s
      timeout: 3s
      retries: 10

  nats:
    image: nats:2.10-alpine
    container_name: scheduler-nats
    command: ["-js", "-sd", "/data", "-m", "8222"]
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - /opt/scheduler/data/nats:/data

  api:
    build:
      context: ..
      dockerfile: ./Dockerfile
      args:
        CMD_PATH: ./cmd/api
    container_name: scheduler-api
    depends_on:
      postgres:
        condition: service_healthy
      nats:
        condition: service_started
    ports:
      - "8080:8080"
    volumes:
      - ./configs/api.yml:/app/config/core.yaml:ro

  scheduler:
    build:
      context: ..
      dockerfile: ./Dockerfile
      args:
        CMD_PATH: ./cmd/scheduler
    container_name: scheduler-scheduler
    depends_on:
      postgres:
        condition: service_healthy
      nats:
        condition: service_started
    volumes:
      - ./configs/scheduler.yml:/app/config/core.yaml:ro

  fetcher-worker:
    build:
      context: ..
      dockerfile: ./Dockerfile
      args:
        CMD_PATH: ./cmd/fetcher-worker
    container_name: scheduler-fetcher
    depends_on:
      scheduler:
        condition: service_started
      nats:
        condition: service_started
    volumes:
      - ./configs/fetcher.yml:/app/config/core.yaml:ro

  delivery-worker:
    build:
      context: ..
      dockerfile: ./Dockerfile
      args:
        CMD_PATH: ./cmd/delivery-worker
    container_name: scheduler-delivery
    depends_on:
      scheduler:
        condition: service_started
      nats:
        condition: service_started
    volumes:
      - ./configs/delivery.yml:/app/config/core.yaml:ro
