// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createJob = `-- name: CreateJob :one

INSERT INTO jobs (
    id,
    name
) VALUES (
    $1, $2
)
RETURNING id
`

type CreateJobParams struct {
	ID   uuid.UUID
	Name string
}

// =========================
// JOBS
// =========================
func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createJob, arg.ID, arg.Name)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createJobIOConfig = `-- name: CreateJobIOConfig :exec

INSERT INTO job_io_configs (
    job_id,
    kind,
    payload,
    header_auth,
    target_url,
    method
) VALUES (
    $1, $2, $3, $4, $5, $6
)
`

type CreateJobIOConfigParams struct {
	JobID      uuid.UUID
	Kind       JobIoKind
	Payload    []byte
	HeaderAuth []byte
	TargetUrl  string
	Method     string
}

// =========================
// IO CONFIGS
// =========================
func (q *Queries) CreateJobIOConfig(ctx context.Context, arg CreateJobIOConfigParams) error {
	_, err := q.db.Exec(ctx, createJobIOConfig,
		arg.JobID,
		arg.Kind,
		arg.Payload,
		arg.HeaderAuth,
		arg.TargetUrl,
		arg.Method,
	)
	return err
}

const createJobSchedule = `-- name: CreateJobSchedule :exec

INSERT INTO job_schedules (
    job_id,
    repeat_interval_sec,
    target_runs,
    last_run_at,
    next_run_at
) VALUES (
    $1, $2, $3, NULL, $4
)
`

type CreateJobScheduleParams struct {
	JobID             uuid.UUID
	RepeatIntervalSec int32
	TargetRuns        int32
	NextRunAt         time.Time
}

// =========================
// SCHEDULE
// =========================
func (q *Queries) CreateJobSchedule(ctx context.Context, arg CreateJobScheduleParams) error {
	_, err := q.db.Exec(ctx, createJobSchedule,
		arg.JobID,
		arg.RepeatIntervalSec,
		arg.TargetRuns,
		arg.NextRunAt,
	)
	return err
}

const deleteJob = `-- name: DeleteJob :exec
DELETE FROM jobs
WHERE id = $1
`

func (q *Queries) DeleteJob(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteJob, id)
	return err
}

const getJob = `-- name: GetJob :one
SELECT
    id,
    name,
    created_at,
    updated_at
FROM jobs
WHERE id = $1
`

func (q *Queries) GetJob(ctx context.Context, id uuid.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJobSchedule = `-- name: GetJobSchedule :one
SELECT
    job_id,
    status,
    repeat_interval_sec,
    done_runs,
    target_runs,
    last_run_at,
    next_run_at,
    created_at,
    updated_at
FROM job_schedules
WHERE job_id = $1
`

func (q *Queries) GetJobSchedule(ctx context.Context, jobID uuid.UUID) (JobSchedule, error) {
	row := q.db.QueryRow(ctx, getJobSchedule, jobID)
	var i JobSchedule
	err := row.Scan(
		&i.JobID,
		&i.Status,
		&i.RepeatIntervalSec,
		&i.DoneRuns,
		&i.TargetRuns,
		&i.LastRunAt,
		&i.NextRunAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listJobIOConfigs = `-- name: ListJobIOConfigs :many
SELECT
    job_id,
    kind,
    payload,
    header_auth,
    target_url,
    method
FROM job_io_configs
WHERE job_id = $1
`

type ListJobIOConfigsRow struct {
	JobID      uuid.UUID
	Kind       JobIoKind
	Payload    []byte
	HeaderAuth []byte
	TargetUrl  string
	Method     string
}

func (q *Queries) ListJobIOConfigs(ctx context.Context, jobID uuid.UUID) ([]ListJobIOConfigsRow, error) {
	rows, err := q.db.Query(ctx, listJobIOConfigs, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJobIOConfigsRow
	for rows.Next() {
		var i ListJobIOConfigsRow
		if err := rows.Scan(
			&i.JobID,
			&i.Kind,
			&i.Payload,
			&i.HeaderAuth,
			&i.TargetUrl,
			&i.Method,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const patchJobIOConfig = `-- name: PatchJobIOConfig :one
UPDATE job_io_configs
SET
    payload = CASE 
        WHEN $1::bool THEN $2 
        ELSE payload
    END,
    target_url = COALESCE($3, target_url),
    method = COALESCE($4, method),
    header_auth = CASE
        WHEN $5::bool THEN $6
        ELSE header_auth
    END
WHERE job_id = $7
  AND kind = $8::job_io_kind
RETURNING job_id
`

type PatchJobIOConfigParams struct {
	SetPayload    bool
	Payload       []byte
	TargetUrl     *string
	Method        *string
	SetHeaderAuth bool
	HeaderAuth    []byte
	JobID         uuid.UUID
	Kind          JobIoKind
}

func (q *Queries) PatchJobIOConfig(ctx context.Context, arg PatchJobIOConfigParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, patchJobIOConfig,
		arg.SetPayload,
		arg.Payload,
		arg.TargetUrl,
		arg.Method,
		arg.SetHeaderAuth,
		arg.HeaderAuth,
		arg.JobID,
		arg.Kind,
	)
	var job_id uuid.UUID
	err := row.Scan(&job_id)
	return job_id, err
}

const patchJobSchedule = `-- name: PatchJobSchedule :one
UPDATE job_schedules
SET
    repeat_interval_sec = COALESCE($1, repeat_interval_sec),
    target_runs = COALESCE($2, target_runs),
    next_run_at = CASE
        WHEN $3::bool THEN $4
        ELSE next_run_at
    END,
    status = CASE 
        WHEN $5::schedule_status IS NOT NULL
            AND status != 'running'
            AND $5::schedule_status != 'error'
        THEN $5::schedule_status
        ELSE status 
    END,
    updated_at = NOW()
WHERE job_id = $6
RETURNING job_id
`

type PatchJobScheduleParams struct {
	RepeatIntervalSec *int32
	TargetRuns        *int32
	SetNextRunAt      bool
	NextRunAt         time.Time
	Status            NullScheduleStatus
	JobID             uuid.UUID
}

func (q *Queries) PatchJobSchedule(ctx context.Context, arg PatchJobScheduleParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, patchJobSchedule,
		arg.RepeatIntervalSec,
		arg.TargetRuns,
		arg.SetNextRunAt,
		arg.NextRunAt,
		arg.Status,
		arg.JobID,
	)
	var job_id uuid.UUID
	err := row.Scan(&job_id)
	return job_id, err
}

const updateJobName = `-- name: UpdateJobName :one
UPDATE jobs
SET
    name = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id
`

type UpdateJobNameParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) UpdateJobName(ctx context.Context, arg UpdateJobNameParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, updateJobName, arg.ID, arg.Name)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const updateJobScheduleStatus = `-- name: UpdateJobScheduleStatus :one
UPDATE job_schedules
SET
    status = CASE 
        WHEN status != 'running' AND $1::schedule_status != 'error' THEN $1
        ELSE status 
    END,
    updated_at = NOW()
WHERE job_id = $2
RETURNING job_id
`

type UpdateJobScheduleStatusParams struct {
	Status ScheduleStatus
	JobID  uuid.UUID
}

func (q *Queries) UpdateJobScheduleStatus(ctx context.Context, arg UpdateJobScheduleStatusParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, updateJobScheduleStatus, arg.Status, arg.JobID)
	var job_id uuid.UUID
	err := row.Scan(&job_id)
	return job_id, err
}
