// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type JobIoKind string

const (
	JobIoKindFetcher JobIoKind = "fetcher"
	JobIoKindDeliver JobIoKind = "deliver"
)

func (e *JobIoKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobIoKind(s)
	case string:
		*e = JobIoKind(s)
	default:
		return fmt.Errorf("unsupported scan type for JobIoKind: %T", src)
	}
	return nil
}

type NullJobIoKind struct {
	JobIoKind JobIoKind
	Valid     bool // Valid is true if JobIoKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJobIoKind) Scan(value interface{}) error {
	if value == nil {
		ns.JobIoKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JobIoKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJobIoKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JobIoKind), nil
}

type ScheduleStatus string

const (
	ScheduleStatusIdle     ScheduleStatus = "idle"
	ScheduleStatusRunning  ScheduleStatus = "running"
	ScheduleStatusError    ScheduleStatus = "error"
	ScheduleStatusDisabled ScheduleStatus = "disabled"
)

func (e *ScheduleStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ScheduleStatus(s)
	case string:
		*e = ScheduleStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ScheduleStatus: %T", src)
	}
	return nil
}

type NullScheduleStatus struct {
	ScheduleStatus ScheduleStatus
	Valid          bool // Valid is true if ScheduleStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullScheduleStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ScheduleStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ScheduleStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullScheduleStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ScheduleStatus), nil
}

type Job struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type JobIoConfig struct {
	JobID     uuid.UUID
	Kind      JobIoKind
	Payload   []byte
	Headers   []byte
	TargetUrl string
	Method    string
	CreatedAt time.Time
}

type JobSchedule struct {
	JobID             uuid.UUID
	Status            ScheduleStatus
	RepeatIntervalSec int32
	TargetRuns        int32
	LastRunAt         *time.Time
	NextRunAt         time.Time
	CreatedAt         time.Time
	UpdatedAt         time.Time
	ScheduledRuns     int32
}
