// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scheduler.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const claimNextJob = `-- name: ClaimNextJob :one
UPDATE job_schedules
SET
    status = 'running',
    scheduled_runs = scheduled_runs + 1,
    last_run_at = NOW(),
    next_run_at = CASE
        WHEN repeat_interval_sec > 0
            THEN NOW() + (repeat_interval_sec * INTERVAL '1 second')
        ELSE NULL
    END,
    updated_at = NOW()
WHERE job_id = (
    SELECT s.job_id
    FROM job_schedules s
    WHERE s.status = 'idle'
      AND s.next_run_at IS NOT NULL
      AND s.next_run_at <= NOW()
      AND (
            s.target_runs IS NULL
            OR s.scheduled_runs < s.target_runs
          )
    ORDER BY s.next_run_at
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
RETURNING job_id
`

func (q *Queries) ClaimNextJob(ctx context.Context) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, claimNextJob)
	var job_id uuid.UUID
	err := row.Scan(&job_id)
	return job_id, err
}
