// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: worker.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getConfig = `-- name: GetConfig :one
SELECT 
    payload, 
    header_auth,
    target_url,
    method
FROM job_io_configs  
WHERE job_id= $1 AND kind = $2
`

type GetConfigParams struct {
	JobID uuid.UUID
	Kind  JobIoKind
}

type GetConfigRow struct {
	Payload    []byte
	HeaderAuth []byte
	TargetUrl  string
	Method     string
}

func (q *Queries) GetConfig(ctx context.Context, arg GetConfigParams) (GetConfigRow, error) {
	row := q.db.QueryRow(ctx, getConfig, arg.JobID, arg.Kind)
	var i GetConfigRow
	err := row.Scan(
		&i.Payload,
		&i.HeaderAuth,
		&i.TargetUrl,
		&i.Method,
	)
	return i, err
}

const setJobStatus = `-- name: SetJobStatus :exec
UPDATE job_schedules
SET status = $1
WHERE job_id = $2
`

type SetJobStatusParams struct {
	Status ScheduleStatus
	JobID  uuid.UUID
}

func (q *Queries) SetJobStatus(ctx context.Context, arg SetJobStatusParams) error {
	_, err := q.db.Exec(ctx, setJobStatus, arg.Status, arg.JobID)
	return err
}
