database:
  url: "${DATABASE_URL}"
  max_connections: 10
  min_connections: 2
  max_connection_lifetime: 1h
  min_connection_lifetime: 15m
  healthcheck_period: 1m

nats:
  url: "${NATS_URL}"

otel:
  endpoint: "${OTEL_EXPORTER_OTLP_ENDPOINT}"
  metrics:
    enable: true

background_tasks:
  hung_jobs_monitor:
    poll_interval: 5m
    schedule_timeout_seconds: 15
    proc_timeout_seconds: 5400

  disable_jobs_monitor:
    poll_interval: 1m

  get_job:
    poll_interval: 1s
    jobs_batch_size: 100
    max_parallel_pushers: 256
